### ISSUE TITLE
Consider adding more maintainers to the image-spec

### ISSUE THREAD

**Issue by caniszczyk** [opencontainers/image-spec#590]
re: @stevvooe response on the mailing list

If I look at contributors: https://github.com/opencontainers/image-spec/graphs/contributors 

@runcom and @xiekeyang may be good choices based on contributions

**Comment by crosbymichael** [comment]
We also need to look at removing existing maintainers that are not contributing anymore.  Its not good enough to just add more.  Alex is a stand up example for when you can no longer perform your duties as a maintainer, you just step down.

I think we have some on the runtime/runc side that have not contributed or voted on anything within 6mo or more or are not sharing the load of work that need to be removed.  They can always come back later when their work or personal lives allow it but staying on as a maintainer and not doing the work is unfair to everyone involved.

**Comment by caniszczyk** [comment]
@crosbymichael sgtm, give me some time to look at the stats via oci.biterg.io to at least issue a report, I don't think we should automatically remove people but maybe ask them every 6-12 months if they become historically inactive

**Comment by crosbymichael** [comment]
@caniszczyk yes, we shouldn't blind side anyone and ideally people just step down when they cannot fulfill the responsibilities but we have rules for removal:

https://github.com/opencontainers/runc/blob/master/MAINTAINERS_GUIDE.md#what-is-expected-of-maintainers

It does not have to be something negative or looked down upon.

**Comment by coolljt0725** [comment]
@caniszczyk   If possible, I'm volunteer to be a maintainer and to help move this project forward  :)

**Comment by xiekeyang** [comment]
@caniszczyk Appreciate your recommendation! I'm so happy to become image-spec maintainer. And I would like to make more research and contribution for this project.

**Comment by runcom** [comment]
> @runcom and @xiekeyang may be good choices based on contributions

:+1: from me

**Comment by jonboulle** [comment]
as well as the existing suggestions I'd like to nominate @cyphar if he's interested.

**Comment by caniszczyk** [comment]
Simply based on contribution history, these three folks make a good fit:

* @runcom 
* @xiekeyang
* @coolljt0725

Do the @opencontainers/image-spec-maintainers want to call for a vote?

After folks are added, I can reach out to some of the inactive maintainers and ask them if they still want to be listed as a maintainer.

**Comment by stevvooe** [comment]
@caniszczyk Before adding new maintainers, I think we need to give the current maintainers a chance to respond on the issue of absenteeism. The problem I called out on the mailing list was not that we don't have enough maintainers; the problem is that the existing maintainers aren't reviewing submissions.

I can see this broken down into two problems:

1. Not enough maintainers to review existing body of work.
2. Blocking on general expertise which may exist with only certain maintainers.

Selecting new maintainers based on contribution experience may address 1, but I am unsure about 2.

**Comment by caniszczyk** [comment]
@stevvooe SGTM! I created https://github.com/opencontainers/image-spec/issues/603 for the current set of maintainers to speak up or step down if they don't have the time anymore. After that, it would be great to consider new maintainers who are active based on contributions. 

The the second issue you mentioned is tough to solve and would love your thoughts on how to address it.

**Comment by wking** [comment]
On Thu, Mar 09, 2017 at 09:21:20AM -0800, Chris Aniszczyk wrote:
> The the second issue you mentioned is tough to solve and would love
> your thoughts on how to address it.

I think the way forward on maintainer-expertise is to identify areas
where there seems to be a shortage and add additional maintainers to
cover those areas.  Getting two experienced LGTMs on a particular
topic seems achievable for topics which impact image-spec.  Are there
areas where experienced maintainers are thin that are missing
candidates?

**Comment by RobDolinMS** [comment]
@caniszczyk Would you mind setting this to milestone==post-v1.0 ?

**Comment by stevvooe** [comment]
@caniszczyk @RobDolinMS I think most of the issues that started this discussion have been addressed. Maintainer participation has been much better as of late. If there are any maintainers who are inactive and would like to step down, we can make a call for that, as well.

**Comment by cyphar** [comment]
I've nominated myself in #709, as I still believe that maintainer participation is still an issue (given how much work both @stevvooe and @vbatts have been doing recently).

**Comment by estesp** [comment]
We're on our second round of this in #834 so this issue can probably be closed @caniszczyk
